
export const LOAD_LESSON = 'LOAD_LESSON';
export const LOAD_LESSON_SUCCESS = 'LOAD_LESSON_SUCCESS';
export const LOAD_LESSON_FAIL = 'LOAD_LESSON_FAIL';

export const UPDATE_LESSON = 'UPDATE_LESSON';
export const UPDATE_LESSON_SUCCESS = 'UPDATE_LESSON_SUCCESS';
export const UPDATE_LESSON_FAIL = 'UPDATE_LESSON_FAIL';

export const UPDATE_LESSON_IMAGE = 'UPDATE_LESSON_IMAGE';
export const UPDATE_LESSON_IMAGE_SUCCESS = 'UPDATE_LESSON_IMAGE_SUCCESS';
export const UPDATE_LESSON_IMAGE_FAIL = 'UPDATE_LESSON_IMAGE_FAIL';

export const DELETE_LESSON = 'DELETE_LESSON';
export const DELETE_LESSON_SUCCESS = 'DELETE_LESSON_SUCCESS';
export const DELETE_LESSON_FAIL = 'DELETE_LESSON_FAIL';

export const LOAD_EXERCISES = 'LOAD_EXERCISES';
export const LOAD_EXERCISES_SUCCESS = 'LOAD_EXERCISES_SUCCESS';
export const LOAD_EXERCISES_FAIL = 'LOAD_EXERCISES_FAIL';

export const UPDATE_EXERCISES = 'UPDATE_EXERCISES';
export const UPDATE_EXERCISES_SUCCESS = 'UPDATE_EXERCISES_SUCCESS';
export const UPDATE_EXERCISES_FAIL = 'UPDATE_EXERCISES_FAIL';

export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const DELETE_EXERCISE_SUCCESS = 'DELETE_EXERCISE_SUCCESS';
export const DELETE_EXERCISE_FAIL = 'DELETE_EXERCISE_FAIL';

export const ADD_NEW_EXERCISE = 'ADD_NEW_EXERCISE';
export const ADD_NEW_EXERCISE_SUCCESS = 'ADD_NEW_EXERCISE_SUCCESS';
export const ADD_NEW_EXERCISE_FAIL = 'ADD_NEW_EXERCISE_FAIL';

export const REORDER_EXERCISE = 'REORDER_EXERCISE';
export const REORDER_EXERCISE_SUCCESS = 'REORDER_EXERCISE_SUCCESS';
export const REORDER_EXERCISE_FAIL = 'REORDER_EXERCISE_FAIL';
