
export const ADD_NEW_LESSON = 'ADD_NEW_LESSON';
export const ADD_NEW_LESSON_SUCCESS = 'ADD_NEW_LESSON_SUCCESS';
export const ADD_NEW_LESSON_FAIL = 'ADD_NEW_LESSON_FAIL';

export const UPDATE_LESSON_IMAGE = 'UPDATE_LESSON_IMAGE';
export const UPDATE_LESSON_IMAGE_SUCCESS = 'UPDATE_LESSON_IMAGE_SUCCESS';
export const UPDATE_LESSON_IMAGE_FAIL = 'UPDATE_LESSON_IMAGE_FAIL';
